#!/usr/bin/with-contenv bash

echo '
******************************************************
******************************************************
*                                                    *
*                                                    *
*          This image has been deprecated            *
*                                                    *
*           Use the multi-arch images at             *
*                                                    *
*               linuxserver/hydra2                   *
*                                                    *
*    https://hub.docker.com/r/linuxserver/hydra2     *
*                                                    *
*   https://github.com/linuxserver/docker-hydra2    *
*                                                    *
*                                                    *
*                                                    *
******************************************************
******************************************************'
